# docker-compose.yml
version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://root:secret@db:5432/moviedb?sslmode=disable"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: moviedb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
