services:
  app:
    image: golang:1.24.6
    container_name: movie_reservation_app
    working_dir: /app
    volumes:
      - .:/app
    command: ["go", "run", "."]
    ports:
      - "8080:8080"
    environment:
      DATABASE_DSN: "host=db user=root password=secret dbname=moviesdb port=5432 sslmode=disable"
    depends_on:
      - db
    # env_file:
    #   - .env

  db:
    image: postgres:15
    container_name: movie_reservation_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: moviesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
